import turtle
m=turtle. Turtle()
turtle.bgcolor("black")
m.up()
m. goto(0, -100)
m.down()
m.begin_fill()
m.fillcolor ("yellow")
m.circle(100)
m.end_fill()
m.up()
m.goto(-30,-45)
m.setheading(-50)
m.width(10)
m. down()
m .circle(40, 120)
m.color("black")
for i in range(-35, 105, 70):
    m.up()
    m.goto(i, 35)
    m.setheading(0)
    m.down()
    m.begin_fill()
    m.circle(10)
    m.end_fill()
m.hideturtle()
turtle.done()
